#! /bin/bash
cd /home/labs/.virtualenvs/mixkey
source bin/activate
cd -
sudo kill `lsof -t -i:8081`
sudo service mysql restart
python ./manage.py runfcgi host=127.0.0.1 port=8081 --settings=mixkey.settings

