#! /bin/bash
sudo kill `lsof -t -i:8081`
sudo service nginx stop
/home/labs/.virtualenvs/mixkey/bin/python /web/sites/mixkey/source/mixkey/manage.py runfcgi host=127.0.0.1 port=8081 --settings=mixkey.settings
sudo service nginx start
sudo service memcached restart
